// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"mu2nyf4c3c","name":"sampleCloudApi","description":"","endpoint":"https://mu2nyf4c3c.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/items","/items/123"]},{"id":"l3je6pwmi1","name":"itemPostingsCRUD","description":"","endpoint":"https://l3je6pwmi1.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/itemPostings","/itemPostings/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:1da932e6-0f5f-4740-9a9e-9dec3255c1ab',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'slugmarket-hosting-mobilehub-1354671785',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd17sctlyh175rt.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-1',
    'aws_dynamodb_table_schemas': [{"tableName":"slugmarket-mobilehub-1354671785-itemPostings","attributes":[{"name":"userId","type":"S"},{"name":"timeAdded","type":"S"},{"name":"category","type":"S"},{"name":"description","type":"S"},{"name":"email","type":"S"},{"name":"isRemoved","type":"BOOL"},{"name":"isSold","type":"BOOL"},{"name":"phoneNumber","type":"S"},{"name":"price","type":"N"},{"name":"seller","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"userId","rangeKey":"timeAdded"}],
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '7676474024044065a5eac5e411b1ec25',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b4927044-3dd1-44a0-801a-672d19ef8d35',
    'aws_project_name': 'SlugMarket',
    'aws_project_region': 'us-west-1',
    'aws_resource_bucket_name': 'slugmarket-deployments-mobilehub-1354671785',
    'aws_resource_name_prefix': 'slugmarket-mobilehub-1354671785',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_iFePCdl6L',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '6j6m1hc5mteducie1833qrbkt0',
}

export default awsmobile;
