// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:30f4aea2-34fd-4907-b350-460cf323ff38',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'slugmarket-hosting-mobilehub-135217890',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2it10xrpswjp4.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-1',
    'aws_dynamodb_table_schemas': [{"tableName":"slugmarket-mobilehub-135217890-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-west-1","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': '6cb078a5b41a464381c9a2b47bd46575',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd10f4845-0ffd-4a76-b88d-0a6c1d11e305',
    'aws_project_name': 'SlugMarket',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'slugmarket-mobilehub-135217890',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_2tqdwWJGx',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '6b3kklnfgdkr17j02dij8adn4f',
}

export default awsmobile;
