// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:be237ae9-35b3-45a4-bce9-8e12199332d0',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'slugmarketv-hosting-mobilehub-1439541682',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd21c5j3odaffce.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-1',
    'aws_dynamodb_table_schemas': [{"tableName":"slugmarketv-mobilehub-1439541682-postedItems","attributes":[{"name":"userId","type":"S"},{"name":"timeAdded","type":"N"},{"name":"category","type":"S"},{"name":"description","type":"S"},{"name":"isSold","type":"BOOL"},{"name":"itemName","type":"S"},{"name":"price","type":"N"},{"name":"seller","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"userId","rangeKey":"timeAdded"}],
    'aws_mobile_analytics_app_id': 'ec1600eda59f44ad9b9a8f929ef1fcc6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '00e55ada-10ff-4e18-b2a3-530a96d40831',
    'aws_project_name': 'SlugMarket-v2',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'slugmarketv-mobilehub-1439541682',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'slugmarketv-userfiles-mobilehub-1439541682',
    'aws_user_files_s3_bucket_region': 'us-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_ywdrbgzdA',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '48bjlef4aqv706p4g8bbves7k3',
}

export default awsmobile;
